/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_reservation (void)
{
  GtkWidget *gestion_reservation;
  GtkWidget *notebook2s;
  GtkWidget *fixeds3;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *cin;
  GtkWidget *telephone;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkWidget *label789;
  GtkWidget *label777;
  GtkWidget *label1254;
  GtkWidget *label2458;
  GtkWidget *label1234;
  GtkWidget *label2525;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *combobox1;
  GtkWidget *retoursalma;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label56;
  GtkWidget *label71;
  GtkWidget *button_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *label60;
  GtkWidget *RESERVATIONVIP;
  GSList *RESERVATIONVIP_group = NULL;
  GtkWidget *label51;
  GtkWidget *label2323;
  GtkWidget *RESERVATIONNORM;
  GtkWidget *label15s;
  GtkWidget *fixed4s;
  GtkWidget *telephone1;
  GtkWidget *prenom1;
  GtkWidget *cin1;
  GtkWidget *nom2;
  GtkWidget *entry_id;
  GtkObject *sjour1_adj;
  GtkWidget *sjour1;
  GtkObject *sannee1_adj;
  GtkWidget *sannee1;
  GtkWidget *buttonverif;
  GtkWidget *button_modifier;
  GtkWidget *label240;
  GtkWidget *label270;
  GtkObject *smois1_adj;
  GtkWidget *smois1;
  GtkWidget *label220;
  GtkWidget *label180;
  GtkWidget *label200;
  GtkWidget *label210;
  GtkWidget *label190;
  GtkWidget *parking1;
  GtkWidget *label260;
  GtkWidget *label230;
  GtkWidget *label16s;
  GtkWidget *fixed5s;
  GtkWidget *id1;
  GtkWidget *msg1;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label311;
  GtkWidget *button_supprimer;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *label62;
  GtkWidget *label72;
  GtkWidget *label17s;
  GtkWidget *fixed11s;
  GtkWidget *label35;
  GtkWidget *button21;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label61;
  GtkWidget *actualisersalma;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed12;
  GtkWidget *treeview11;
  GtkWidget *label18s;
  GtkWidget *fixed13s;
  GtkWidget *label65;
  GtkWidget *comboboxentry1;
  GtkWidget *label67;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport3;
  GtkWidget *fixed16;
  GtkWidget *treeview22;
  GtkWidget *AFFICHER;
  GtkWidget *label19s;

  gestion_reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_reservation), _("window2"));

  notebook2s = gtk_notebook_new ();
  gtk_widget_show (notebook2s);
  gtk_container_add (GTK_CONTAINER (gestion_reservation), notebook2s);

  fixeds3 = gtk_fixed_new ();
  gtk_widget_show (fixeds3);
  gtk_container_add (GTK_CONTAINER (notebook2s), fixeds3);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixeds3), nom, 208, 104);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixeds3), prenom, 210, 160);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixeds3), cin, 208, 216);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  telephone = gtk_entry_new ();
  gtk_widget_show (telephone);
  gtk_fixed_put (GTK_FIXED (fixeds3), telephone, 208, 336);
  gtk_widget_set_size_request (telephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephone), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixeds3), jour, 912, 64);
  gtk_widget_set_size_request (jour, 72, 32);

  annee_adj = gtk_adjustment_new (1922, 2024, 2025, 1, 10, 0);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixeds3), annee, 904, 184);
  gtk_widget_set_size_request (annee, 72, 32);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixeds3), mois, 920, 128);
  gtk_widget_set_size_request (mois, 60, 27);

  label789 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label789);
  gtk_fixed_put (GTK_FIXED (fixeds3), label789, 88, 104);
  gtk_widget_set_size_request (label789, 50, 20);

  label777 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label777);
  gtk_fixed_put (GTK_FIXED (fixeds3), label777, 80, 160);
  gtk_widget_set_size_request (label777, 75, 17);

  label1254 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label1254);
  gtk_fixed_put (GTK_FIXED (fixeds3), label1254, 88, 224);
  gtk_widget_set_size_request (label1254, 41, 16);

  label2458 = gtk_label_new (_("nom parking : "));
  gtk_widget_show (label2458);
  gtk_fixed_put (GTK_FIXED (fixeds3), label2458, 80, 280);
  gtk_widget_set_size_request (label2458, 100, 17);

  label1234 = gtk_label_new (_("telephone"));
  gtk_widget_show (label1234);
  gtk_fixed_put (GTK_FIXED (fixeds3), label1234, 40, 344);
  gtk_widget_set_size_request (label1234, 150, 17);

  label2525 = gtk_label_new (_("date de r\303\251servation :"));
  gtk_widget_show (label2525);
  gtk_fixed_put (GTK_FIXED (fixeds3), label2525, 624, 80);
  gtk_widget_set_size_request (label2525, 150, 17);
  gtk_misc_set_padding (GTK_MISC (label2525), 0, 2);

  label68 = gtk_label_new (_("jour"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixeds3), label68, 840, 72);
  gtk_widget_set_size_request (label68, 56, 24);

  label69 = gtk_label_new (_("mois "));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixeds3), label69, 784, 128);
  gtk_widget_set_size_request (label69, 56, 24);

  label70 = gtk_label_new (_("annee "));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixeds3), label70, 840, 184);
  gtk_widget_set_size_request (label70, 56, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixeds3), combobox1, 216, 272);
  gtk_widget_set_size_request (combobox1, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingF"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");

  retoursalma = gtk_toggle_button_new ();
  gtk_widget_show (retoursalma);
  gtk_fixed_put (GTK_FIXED (fixeds3), retoursalma, 0, 0);
  gtk_widget_set_size_request (retoursalma, 109, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retoursalma), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox2), label56, FALSE, FALSE, 0);

  label71 = gtk_label_new ("");
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixeds3), label71, 632, 536);
  gtk_widget_set_size_request (label71, 296, 96);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixeds3), button_ajouter, 720, 504);
  gtk_widget_set_size_request (button_ajouter, 90, 31);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  label60 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox6), label60, FALSE, FALSE, 0);

  RESERVATIONVIP = gtk_radio_button_new_with_mnemonic (NULL, _("reservation vip"));
  gtk_widget_show (RESERVATIONVIP);
  gtk_fixed_put (GTK_FIXED (fixeds3), RESERVATIONVIP, 96, 504);
  gtk_widget_set_size_request (RESERVATIONVIP, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RESERVATIONVIP), RESERVATIONVIP_group);
  RESERVATIONVIP_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RESERVATIONVIP));

  label51 = gtk_label_new ("");
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixeds3), label51, 752, 352);
  gtk_widget_set_size_request (label51, 128, 40);

  label2323 = gtk_label_new (_("id de reservation "));
  gtk_widget_show (label2323);
  gtk_fixed_put (GTK_FIXED (fixeds3), label2323, 496, 376);
  gtk_widget_set_size_request (label2323, 220, 17);

  RESERVATIONNORM = gtk_radio_button_new_with_mnemonic (NULL, _("reservation normale"));
  gtk_widget_show (RESERVATIONNORM);
  gtk_fixed_put (GTK_FIXED (fixeds3), RESERVATIONNORM, 96, 464);
  gtk_widget_set_size_request (RESERVATIONNORM, 168, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RESERVATIONNORM), RESERVATIONVIP_group);
  RESERVATIONVIP_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RESERVATIONNORM));

  label15s = gtk_label_new (_("Ajouter une r\303\251servation \360\237\223\245"));
  gtk_widget_show (label15s);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2s), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2s), 0), label15s);
  gtk_widget_set_size_request (label15s, 190, -1);

  fixed4s = gtk_fixed_new ();
  gtk_widget_show (fixed4s);
  gtk_container_add (GTK_CONTAINER (notebook2s), fixed4s);

  telephone1 = gtk_entry_new ();
  gtk_widget_show (telephone1);
  gtk_fixed_put (GTK_FIXED (fixed4s), telephone1, 208, 368);
  gtk_widget_set_size_request (telephone1, 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephone1), 8226);

  prenom1 = gtk_entry_new ();
  gtk_widget_show (prenom1);
  gtk_fixed_put (GTK_FIXED (fixed4s), prenom1, 208, 152);
  gtk_widget_set_size_request (prenom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom1), 8226);

  cin1 = gtk_entry_new ();
  gtk_widget_show (cin1);
  gtk_fixed_put (GTK_FIXED (fixed4s), cin1, 208, 216);
  gtk_widget_set_size_request (cin1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin1), 8226);

  nom2 = gtk_entry_new ();
  gtk_widget_show (nom2);
  gtk_fixed_put (GTK_FIXED (fixed4s), nom2, 208, 104);
  gtk_widget_set_size_request (nom2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom2), 8226);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed4s), entry_id, 208, 48);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  sjour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  sjour1 = gtk_spin_button_new (GTK_ADJUSTMENT (sjour1_adj), 1, 0);
  gtk_widget_show (sjour1);
  gtk_fixed_put (GTK_FIXED (fixed4s), sjour1, 760, 128);
  gtk_widget_set_size_request (sjour1, 60, 27);

  sannee1_adj = gtk_adjustment_new (1, 2024, 2027, 1, 10, 0);
  sannee1 = gtk_spin_button_new (GTK_ADJUSTMENT (sannee1_adj), 1, 0);
  gtk_widget_show (sannee1);
  gtk_fixed_put (GTK_FIXED (fixed4s), sannee1, 952, 128);
  gtk_widget_set_size_request (sannee1, 60, 27);

  buttonverif = gtk_button_new_with_mnemonic (_("verifier "));
  gtk_widget_show (buttonverif);
  gtk_fixed_put (GTK_FIXED (fixed4s), buttonverif, 416, 40);
  gtk_widget_set_size_request (buttonverif, 74, 29);

  button_modifier = gtk_button_new_with_mnemonic (_("Modifier \342\234\217\357\270\217 "));
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4s), button_modifier, 680, 528);
  gtk_widget_set_size_request (button_modifier, 100, 31);

  label240 = gtk_label_new (_("date de r\303\251servation :"));
  gtk_widget_show (label240);
  gtk_fixed_put (GTK_FIXED (fixed4s), label240, 592, 136);
  gtk_widget_set_size_request (label240, 150, 17);

  label270 = gtk_label_new ("");
  gtk_widget_show (label270);
  gtk_fixed_put (GTK_FIXED (fixed4s), label270, 504, 24);
  gtk_widget_set_size_request (label270, 184, 48);

  smois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  smois1 = gtk_spin_button_new (GTK_ADJUSTMENT (smois1_adj), 1, 0);
  gtk_widget_show (smois1);
  gtk_fixed_put (GTK_FIXED (fixed4s), smois1, 864, 128);
  gtk_widget_set_size_request (smois1, 60, 27);

  label220 = gtk_label_new (_("nom parking : "));
  gtk_widget_show (label220);
  gtk_fixed_put (GTK_FIXED (fixed4s), label220, 88, 288);
  gtk_widget_set_size_request (label220, 100, 17);

  label180 = gtk_label_new (_("id"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed4s), label180, 120, 56);
  gtk_widget_set_size_request (label180, 49, 17);

  label200 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed4s), label200, 112, 160);
  gtk_widget_set_size_request (label200, 75, 17);

  label210 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label210);
  gtk_fixed_put (GTK_FIXED (fixed4s), label210, 120, 224);
  gtk_widget_set_size_request (label210, 49, 17);

  label190 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label190);
  gtk_fixed_put (GTK_FIXED (fixed4s), label190, 128, 104);
  gtk_widget_set_size_request (label190, 50, 20);

  parking1 = gtk_combo_box_new_text ();
  gtk_widget_show (parking1);
  gtk_fixed_put (GTK_FIXED (fixed4s), parking1, 216, 280);
  gtk_widget_set_size_request (parking1, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingF"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), "");

  label260 = gtk_label_new ("");
  gtk_widget_show (label260);
  gtk_fixed_put (GTK_FIXED (fixed4s), label260, 544, 568);
  gtk_widget_set_size_request (label260, 328, 72);

  label230 = gtk_label_new ("");
  gtk_widget_show (label230);
  gtk_fixed_put (GTK_FIXED (fixed4s), label230, 88, 376);
  gtk_widget_set_size_request (label230, 90, 17);

  label16s = gtk_label_new (_("Modifier une r\303\251servation \342\234\217\357\270\217 "));
  gtk_widget_show (label16s);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2s), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2s), 1), label16s);
  gtk_widget_set_size_request (label16s, 190, -1);

  fixed5s = gtk_fixed_new ();
  gtk_widget_show (fixed5s);
  gtk_container_add (GTK_CONTAINER (notebook2s), fixed5s);

  id1 = gtk_entry_new ();
  gtk_widget_show (id1);
  gtk_fixed_put (GTK_FIXED (fixed5s), id1, 528, 304);
  gtk_widget_set_size_request (id1, 296, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (id1), 8226);

  msg1 = gtk_label_new ("");
  gtk_widget_show (msg1);
  gtk_fixed_put (GTK_FIXED (fixed5s), msg1, 1000, 104);
  gtk_widget_set_size_request (msg1, 216, 184);

  label32 = gtk_label_new (_("\303\212tes-vous s\303\273r de vouloir supprimer cette r\303\251servation ? "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5s), label32, 528, 408);
  gtk_widget_set_size_request (label32, 370, 17);

  label33 = gtk_label_new (_("NB \360\237\223\214 : toute personne qui effectue une r\303\251servation et ne se pr\303\251sente\n pas sera sanctionn\303\251e par une interdiction de r\303\251servation d'un mois . "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5s), label33, 472, 432);
  gtk_widget_set_size_request (label33, 480, 35);

  label311 = gtk_label_new (_("donner l'identifiant de la r\303\251servation\nque souhaitez vous supprimer \360\237\206\224"));
  gtk_widget_show (label311);
  gtk_fixed_put (GTK_FIXED (fixed5s), label311, 296, 216);
  gtk_widget_set_size_request (label311, 260, 36);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5s), button_supprimer, 672, 528);
  gtk_widget_set_size_request (button_supprimer, 110, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  label62 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox8), label62, FALSE, FALSE, 0);

  label72 = gtk_label_new ("");
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed5s), label72, 616, 568);
  gtk_widget_set_size_request (label72, 248, 72);

  label17s = gtk_label_new (_("Supprimer une r\303\251servation \360\237\227\221\357\270\217"));
  gtk_widget_show (label17s);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2s), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2s), 2), label17s);
  gtk_widget_set_size_request (label17s, 200, -1);

  fixed11s = gtk_fixed_new ();
  gtk_widget_show (fixed11s);
  gtk_container_add (GTK_CONTAINER (notebook2s), fixed11s);

  label35 = gtk_label_new (_("voici la liste des r\303\251servations . si vous avez une r\303\251clamation \nn'hesitez pas a contacter notre service client \342\255\220\357\270\217"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed11s), label35, 56, 72);
  gtk_widget_set_size_request (label35, 450, 35);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed11s), button21, 992, 600);
  gtk_widget_set_size_request (button21, 230, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button21), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("merci pour votre vesite \360\237\214\237\360\237\230\212"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox7), label61, FALSE, FALSE, 0);

  actualisersalma = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (actualisersalma);
  gtk_fixed_put (GTK_FIXED (fixed11s), actualisersalma, 272, 496);
  gtk_widget_set_size_request (actualisersalma, 90, 32);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed11s), scrolledwindow1, 376, 128);
  gtk_widget_set_size_request (scrolledwindow1, 816, 408);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed12);

  treeview11 = gtk_tree_view_new ();
  gtk_widget_show (treeview11);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview11, 0, 0);
  gtk_widget_set_size_request (treeview11, 808, 400);

  label18s = gtk_label_new (_("Afficher les r\303\251servations \360\237\221\200  "));
  gtk_widget_show (label18s);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2s), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2s), 3), label18s);
  gtk_widget_set_size_request (label18s, 220, 22);

  fixed13s = gtk_fixed_new ();
  gtk_widget_show (fixed13s);
  gtk_container_add (GTK_CONTAINER (notebook2s), fixed13s);

  label65 = gtk_label_new (_("choisissez un parking "));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed13s), label65, 520, 544);
  gtk_widget_set_size_request (label65, 180, 22);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed13s), comboboxentry1, 704, 536);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking A "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking C "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking D "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking E "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking F "));

  label67 = gtk_label_new (_("v oici la liste des parkings tri\303\251 "));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed13s), label67, 200, 40);
  gtk_widget_set_size_request (label67, 240, 24);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed13s), scrolledwindow3, 272, 72);
  gtk_widget_set_size_request (scrolledwindow3, 872, 440);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport3);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed16);

  treeview22 = gtk_tree_view_new ();
  gtk_widget_show (treeview22);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview22, 0, 0);
  gtk_widget_set_size_request (treeview22, 856, 424);

  AFFICHER = gtk_button_new_with_mnemonic (_("AFFICHER"));
  gtk_widget_show (AFFICHER);
  gtk_fixed_put (GTK_FIXED (fixed13s), AFFICHER, 176, 480);
  gtk_widget_set_size_request (AFFICHER, 88, 32);

  label19s = gtk_label_new (_("parking tri\303\251s \360\237\227\223\357\270\217"));
  gtk_widget_show (label19s);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2s), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2s), 4), label19s);
  gtk_widget_set_size_request (label19s, 200, -1);

  g_signal_connect ((gpointer) retoursalma, "clicked",
                    G_CALLBACK (on_retoursalma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonverif, "clicked",
                    G_CALLBACK (on_buttonverif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualisersalma, "clicked",
                    G_CALLBACK (on_actualisersalma_clicked),
                    NULL);
  g_signal_connect ((gpointer) AFFICHER, "clicked",
                    G_CALLBACK (on_AFFICHER_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_reservation, gestion_reservation, "gestion_reservation");
  GLADE_HOOKUP_OBJECT (gestion_reservation, notebook2s, "notebook2s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixeds3, "fixeds3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, nom, "nom");
  GLADE_HOOKUP_OBJECT (gestion_reservation, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (gestion_reservation, cin, "cin");
  GLADE_HOOKUP_OBJECT (gestion_reservation, telephone, "telephone");
  GLADE_HOOKUP_OBJECT (gestion_reservation, jour, "jour");
  GLADE_HOOKUP_OBJECT (gestion_reservation, annee, "annee");
  GLADE_HOOKUP_OBJECT (gestion_reservation, mois, "mois");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label789, "label789");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label777, "label777");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label1254, "label1254");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label2458, "label2458");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label1234, "label1234");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label2525, "label2525");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label68, "label68");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label69, "label69");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label70, "label70");
  GLADE_HOOKUP_OBJECT (gestion_reservation, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, retoursalma, "retoursalma");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label71, "label71");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestion_reservation, RESERVATIONVIP, "RESERVATIONVIP");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label2323, "label2323");
  GLADE_HOOKUP_OBJECT (gestion_reservation, RESERVATIONNORM, "RESERVATIONNORM");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label15s, "label15s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed4s, "fixed4s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, telephone1, "telephone1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, prenom1, "prenom1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, cin1, "cin1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, nom2, "nom2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (gestion_reservation, sjour1, "sjour1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, sannee1, "sannee1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, buttonverif, "buttonverif");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label240, "label240");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label270, "label270");
  GLADE_HOOKUP_OBJECT (gestion_reservation, smois1, "smois1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label220, "label220");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label180, "label180");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label200, "label200");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label210, "label210");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label190, "label190");
  GLADE_HOOKUP_OBJECT (gestion_reservation, parking1, "parking1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label260, "label260");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label230, "label230");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label16s, "label16s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed5s, "fixed5s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, id1, "id1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, msg1, "msg1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label311, "label311");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label62, "label62");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label72, "label72");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label17s, "label17s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed11s, "fixed11s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button21, "button21");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestion_reservation, actualisersalma, "actualisersalma");
  GLADE_HOOKUP_OBJECT (gestion_reservation, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (gestion_reservation, treeview11, "treeview11");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label18s, "label18s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed13s, "fixed13s");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_reservation, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label67, "label67");
  GLADE_HOOKUP_OBJECT (gestion_reservation, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (gestion_reservation, treeview22, "treeview22");
  GLADE_HOOKUP_OBJECT (gestion_reservation, AFFICHER, "AFFICHER");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label19s, "label19s");

  return gestion_reservation;
}

